apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: boutique
  template:
    metadata:
      labels:
        app: boutique
    spec:
      containers:
      - name: boutique
        image: krishna100radha/boutique-app:latest
        ports:
        - containerPort: 80