apiVersion: v1
kind: Service
metadata:
  name: boutique-service
spec:
  type: NodePort
  selector:
    app: boutique
  ports:
    - port: 80
      targetPort: 80
      # ❌ REMOVE this line
      # nodePort: 30007